apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
  namespace: prod-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.27
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-logs
      mountPath: /logs
  volumes:
  - name: host-logs
    hostPath:
      path: /var/log
      type: Directory
