apiVersion: v1
kind: Pod
metadata:
  name: podcertificate-pod
  namespace: bankapp-staging
spec:
  serviceAccountName: default
  containers:
  - name: main
    image: debian:stable-slim
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: my-x509-credentials
      mountPath: /var/run/my-x509-credentials
      readOnly: true
  volumes:
  - name: my-x509-credentials
    projected:
      defaultMode: 0420
      sources:
      - podCertificate:
          keyType: ED25519
          signerName: coolcert.example.com/foo
          credentialBundlePath: credentialbundle.pem
          userAnnotations:
            example.com/annotation1: "value1"
            example.com/annotation2: "value2"
