apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: bankapp-envoy-config
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: bankapp-envoy-config
  namespace: envoy-gateway-system
spec:
  concurrency: 4
  logging:
    level:
      default: info
  telemetry:
    metrics:
      prometheus:
        disable: false
